name: mcumgr_flutter_example
description: Demonstrates how to use the mcumgr_flutter plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  platform: ^3.1.0
  flutter_blue_plus: ^1.17.0  
  nordic_dfu: ^4.0.0
  file_picker: ^4.0.10
  permission_handler: ^11.0.0
  mcumgr: ^0.0.3
  rxdart: ^0.27.7
  
  path: ^1.8.0
  flutter_archive: ^4.0.1
  path_provider: ^2.0.5
  open_app_settings: ^2.0.1
  uuid: ^3.0.4
  json_serializable: ^5.0.2
  flutter:
    sdk: flutter
  mcumgr_flutter:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
dependency_overrides:
  rxdart: ^0.27.7
# dependency_overrides:
#   flutter_blue:
#     path: ../../flutter_blue/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/file.zip

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
